### ISSUE TITLE
Terkadang tidak bisa mengirim pesan ke group

### ISSUE THREAD

**Issue by ahmadkeren** [hdiiofficial/WhatsApp-MD#1]
Bang, pernah gak alamin error dimana mulanya botnya bisa ngirim pesan ke group, tapi terkadang gak bisa..
Kalau chat pribadi gak ada masalah..
#methodnya ke run sampai akhir gak ada error, tapi di m.reply(pesan) atau conn.sendMessage(...) nya gak ada respon..
#errornya kadang-kadang muncul kadang enggak

**Comment by hdiiofficial** [comment]
Kagak si ehehe
